In [1]:
using StaticArrays
using LinearAlgebra

In [162]:
a = 1.0
b = 3.0
c = 1.0
d = 5.0
xr = -1.6
r = 0.01
s = 5.0
I = 4.0
vs = 2.0

k1= -0.17
k2 = -0.17
k = 0.11111111



λ = 10
θ = -0.25

Γ(x) = 1.0 / ( 1.0 + exp( -10.0 * ( x  - ( - 0.25 ) ) ) )

Γ (generic function with 1 method)

In [163]:
x1, y1, z1 = -0.5, -1.7249089410449048, 4.3088559083633
x2, y2, z2 = -0.7382288183273402, -1.7249089410449048, 4.3088559083633

(-0.7382288183273402, -1.7249089410449048, 4.3088559083633)

In [164]:
x1_x1 = 2 * b * x1 - 3 * a^2 * x1 - k1 * ( 1 - vs ) * Γ(x2) + k * (x2 - 1)
x1_y1 = 1
x1_z1 = -1

y1_x1 = -2 * d * x1
y1_y1 = -1
y1_z1 = 0

z1_x1 = r * s
z1_y1 = 0
z1_z1 = -r

x1_x2 = -k1 * (x1 - vs) * Γ(x2) + k
x2_x1 = -k2 * (x2 - vs) * Γ(x1) + k


x2_x2 = 2 * b * x2 - 3 * a^2 * x2 - k2 * ( 1 - vs ) * Γ(x1) + k * (x1 - 1)
x2_y2 = 1
x2_z2 = -1

y2_x2 = -2 * d * x2
y2_y2 = -1
y2_z2 = -

z2_x2 = r * s
z2_y2 = 0
z2_z2 = -r

-0.01

In [165]:
Jac = zeros(6, 6)

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [166]:
Jac[1, 1] = 2 * b * x1 - 3 * a * x1^2 - k1 * Γ(x2) - k
Jac[1, 2] = 1
Jac[1, 3] = -1

Jac[2, 1] = -2 * d * x1
Jac[2, 2] = -1
Jac[2, 3] = 0

Jac[3, 1] = r * s
Jac[3, 2] = 0
Jac[3, 3] = -r

Jac[1, 4] = -k1 * (x1 - vs) * Γ(x2) + k
Jac[4, 1] = -k2 * (x2 - vs) * Γ(x1) + k


Jac[4, 4] = 2 * b * x2 - 3 * a * x2^2 - k2 * Γ(x1) - k
Jac[4, 5] = 1
Jac[4, 6] = -1

Jac[5, 4] = -2 * d * x2
Jac[5, 5] = -1
Jac[5, 6] = 0

Jac[6, 4] = r * s
Jac[6, 5] = 0
Jac[6, 6] = -r

-0.01

In [167]:
Jac

6×6 Matrix{Float64}:
 -3.85983     1.0  -1.0    0.107914   0.0   0.0
  5.0        -1.0   0.0    0.0        0.0   0.0
  0.05        0.0  -0.01   0.0        0.0   0.0
  0.0757992   0.0   0.0   -6.16253    1.0  -1.0
  0.0         0.0   0.0    7.38229   -1.0   0.0
  0.0         0.0   0.0    0.05       0.0  -0.01

In [169]:
eigvals(Jac)

6-element Vector{ComplexF64}:
   -7.325767081332564 + 0.0im
   -5.074325982384627 + 0.0im
 0.040572553454105466 + 0.0im
  0.07454896282659157 - 0.013994878671519849im
  0.07454896282659157 + 0.013994878671519849im
   0.1680568279981496 + 0.0im